# Generated by Django 2.2.4 on 2019-08-09 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edited',
            field=models.DateField(default=datetime.datetime(2019, 8, 9, 19, 43, 50, 821961)),
            preserve_default=False,
        ),
    ]
